---
title: "Wickham, Hadley - ggplot2: Elegant Graphics for Data Analysis (3rd ed.), Chapter 6 - Maps"
author: "Original Code: Hadley Wickham (except Taro Mieno for Raster Images, Duncan Murdoch for rgl and Dr. Dominic Royé for OpenStreetMaps) | Modifications: Antti Rask"
date: "2023-01-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 6 Maps

```{r}
library(tidyverse)
library(conflicted)
  conflict_prefer("filter", "dplyr")
  conflict_prefer("select", "dplyr")
```

## 6.1 Polygon maps

```{r}
mi_counties <- map_data("county", "michigan") %>%
  as_tibble() %>%
  select(lon = long, lat, group, id = subregion)
  
head(mi_counties)
```

```{r}
p <- mi_counties %>%
  ggplot(aes(lon, lat, group = group))

p +
  geom_point(size = .25, show.legend = FALSE) +
  coord_sf()
  
p +
  geom_polygon() +
  coord_sf()

p +
  geom_polygon(
    fill = NA, 
    color = "grey50"
  ) + 
  coord_sf()
```

## 6.2 Simple features map

```{r}
library(ozmaps)
library(sf)

oz_states <- ozmap_states
oz_states

oz_states %>%
  ggplot() + 
  geom_sf() + 
  coord_sf()
```

### 6.2.1 Layered maps

```{r}
library(rmapshaper)

oz_states <- ozmap_states %>%
  filter(NAME != "Other Territories")

oz_votes <- ms_simplify(abs_ced)

ggplot() + 
  geom_sf(
    data        = oz_states,
    mapping     = aes(fill = NAME),
    show.legend = FALSE
  ) +
  geom_sf(data = oz_votes, fill = NA) + 
  coord_sf()
```

### 6.2.2 Labelled maps

```{r}
# Filter electorates in the Sydney metropolitan region
sydney_map <- abs_ced %>%
  filter(
    NAME %in% c(
      "Sydney",
      "Wentworth",
      "Warringah",
      "Kingsford Smith",
      "Grayndler",
      "Lowe",
      "North Sydney",
      "Barton",
      "Bradfield",
      "Banks",
      "Blaxland",
      "Reid",
      "Watson",
      "Fowler",
      "Werriwa",
      "Prospect",
      "Parramatta",
      "Bennelong",
      "Mackellar",
      "Greenway",
      "Mitchell",
      "Chifley",
      "McMahon"
    )
  )

# Draw the electoral map of Sydney
sydney_map %>%
ggplot() +
  geom_sf(aes(fill = NAME), show.legend = FALSE) + 
  coord_sf(
    xlim = c(150.97, 151.3),
    ylim = c(-33.98, -33.79)
  ) + 
  geom_sf_label(
    aes(label     = NAME),
    label.padding = unit(1, "mm")
  )

# From the book:
# "The warning message is worth noting. Internally geom_sf_label() uses the function st_point_on_surface() from the sf package to place labels, and the warning message occurs because most algorithms used by sf to compute geometric quantities (e.g., centroids, interior points) are based on an assumption that the points lie in on a flat two dimensional surface and parameterised with Cartesian co-ordinates. This assumption is not strictly warranted, and in some cases (e.g., regions near the poles) calculations that treat longitude and latitude in this way will give erroneous answers. For this reason, the sf package produces warning messages when it relies on this approximation."
```

### 6.2.3 Adding other geoms

```{r}
oz_capitals <- tribble( 
  ~city,           ~lat,     ~lon,
  "Sydney",    -33.8688, 151.2093,  
  "Melbourne", -37.8136, 144.9631, 
  "Brisbane",  -27.4698, 153.0251, 
  "Adelaide",  -34.9285, 138.6007, 
  "Perth",     -31.9505, 115.8605, 
  "Hobart",    -42.8821, 147.3272, 
  "Canberra",  -35.2809, 149.1300, 
  "Darwin",    -12.4634, 130.8456, 
)

ggplot() + 
  geom_sf(data = oz_votes) + 
  geom_sf(
    data  = oz_states,
    color = "black",
    fill  = NA
  ) + 
  geom_point(
    data    = oz_capitals,
    mapping = aes(x = lon, y = lat), color = "red") + 
  coord_sf()
```

## 6.3 Map projections

```{r}
st_crs(oz_votes)

st_crs(oz_votes) == st_crs(4283)
```

```{r}
p <- oz_votes %>%
  ggplot() +
  geom_sf()

p

p +
  coord_sf(crs = st_crs(3112))
```

## 6.4 Working with sf data

```{r}
edenmonaro <- abs_ced %>%
  filter(NAME == "Eden-Monaro")

p <- edenmonaro %>% 
  ggplot() +
  geom_sf()

p + 
  coord_sf(
    xlim = c(147.75, 150.25),
    ylim = c(-37.5, -34.5)
  ) 

p +
  coord_sf(
    xlim = c(150, 150.25),
    ylim = c(-36.3, -36)
  ) 
```

```{r}
edenmonaro_geometry <- edenmonaro %>% 
  pull(geometry)

st_bbox(edenmonaro_geometry)
```

```{r}
edenmonaro_geometry
```

```{r}
st_cast(edenmonaro_geometry, "POLYGON")
```

```{r}
dawson <- abs_ced %>% 
  filter(NAME == "Dawson") %>% 
  pull(geometry)

dawson

dawson %>% 
  ggplot() + 
  geom_sf() +
  coord_sf()
```

```{r}
dawson <- st_cast(dawson, "POLYGON")

which.max(st_area(dawson))

dawson[-69] %>%
  ggplot() + 
  geom_sf() + 
  coord_sf()
```

## 6.5 Raster maps

```{r}
library(terra)
library(weatherOz)

# Option 1
avail <- get_available_imagery(product_id = "IDE00425")

i <- get_satellite_imagery(product_id = avail, scans = 1)

plot(i)
```

```{r}
library(stars)

# Option 2

avail <- get_available_imagery(product_id = "IDE00425")

# Loop through all available images
# 
for (index in 1:1) {
  i <- get_satellite_imagery(product_id = avail[index], scans = 1)
  
  # Save the satellite imagery as a .tif file with a unique name
  output_file <- str_c("img/satellite_imagery_", index, ".tif")
  writeRaster(i, output_file, overwrite = TRUE)
}

sat_vis <- read_stars(
  "img/satellite_imagery_1.tif", 
  RasterIO = list(nBufXSize = 600, nBufYSize = 600)
)

sat_vis

ggplot() + 
  geom_stars(data = sat_vis) + 
  coord_equal() +
  theme_void()
```

```{r}
ggplot() + 
  geom_stars(data = sat_vis, show.legend = FALSE) +
  facet_wrap(vars(band)) + 
  scale_fill_gradient(low = "black", high = "white") +
  coord_equal() +
  theme_void()
```

```{r}
oz_states <- st_transform(oz_states, crs = st_crs(sat_vis))

ggplot() + 
  geom_stars(data = sat_vis, show.legend = FALSE) +
  geom_sf(data = oz_states, fill = NA, color = "white") + 
  coord_sf() + 
  scale_fill_gradient(low = "black", high = "white") +
  theme_void()
```

```{r}
cities <- oz_capitals %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326, remove = FALSE)

cities <- st_transform(cities, st_crs(sat_vis))

ggplot() + 
  geom_stars(data = sat_vis, show.legend = FALSE) +
  geom_sf(data = oz_states, fill = NA, color = "white") + 
  geom_sf(data = cities, color = "red") +
  geom_sf_text(data = cities, mapping = aes(label = city), color = "white") + 
  scale_fill_gradient(low = "black", high = "white") +
  coord_sf() +
  theme_void()
```

## 6.X OpenStreetMap with Dr. Dominic Royé

https://dominicroye.github.io/en/2018/accessing-openstreetmap-data-with-r/

```{r}
library(osmdata)
library(ggmap)

# The first five features
available_features() %>% 
  head()

# Amenities
available_tags("amenity") %>% 
  head()

# Shops
available_tags("shop") %>% 
  head()
```

```{r}
# Building the query
q <- getbb("Madrid") %>%
  opq() %>%
  add_osm_feature("amenity", "cinema")

# Query structure
q %>% 
str() 
```

```{r}
cinema <- osmdata_sf(q)
cinema
```

```{r}
# Our background map
mad_map <- get_map(
  getbb("Madrid"),
  maptype = "toner-background",
  source  = "stamen"
)

# Final map
mad_map %>%
  ggmap() +
  geom_sf(
    data        = cinema$osm_points,
    inherit.aes = FALSE,
    color       = "#238443",
    fill        = "#004529",
    alpha       = .5,
    size        = 4,
    shape       = 21
  ) +
  labs(
    x = "",
    y = ""
  )
```

```{r}
# Bounding box for the Iberian Peninsula
m <- c(-10, 30, 5, 46)

# Building the query
q <- m %>% 
  opq(timeout = 25*100) %>%
  add_osm_feature("name", "Mercadona") %>%
  add_osm_feature("shop", "supermarket")

# Query
mercadona <- osmdata_sf(q)

# Final map
ggplot(mercadona$osm_points) +
  geom_sf(
    color = "#08519c",
    fill  = "#08306b",
    alpha = .5,
    size  = 1,
    shape = 21
    ) +
  theme_void()
```
