---
title: "Wickham, Hadley - ggplot2: Elegant Graphics for Data Analysis (3rd ed.), Chapter 17 - Faceting"
author: "Original Code: Hadley Wickham | Modifications: Antti Rask"
date: "2023-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 17 Faceting

```{r}
library(tidyverse)
library(conflicted)
  conflict_prefer("filter", "dplyr")
  conflict_prefer("select", "dplyr")
```

```{r}
mpg2 <- mpg %>%
  # subset -> filter
  filter(cyl != 5 & drv %in% c("4", "f") & class != "2seater")
```

## 17.1 Facet wrap

```{r}
base <- mpg2 %>% 
  ggplot(aes(displ, hwy)) + 
  geom_blank() + 
  labs(
    x = NULL,
    y = NULL
  )

base +
  facet_wrap(
    vars(class),
    ncol = 3
  )

base + facet_wrap(
  vars(class),
  ncol     = 3,
  as.table = FALSE
)

base +
  facet_wrap(
    vars(class),
    nrow = 3
  )

base +
  facet_wrap(
    vars(class),
    nrow = 3,
    dir  = "v"
  )
```

## 17.2 Facet grid

```{r}
base +
  facet_grid(cols = vars(cyl))

base +
  facet_grid(rows = vars(drv))

base +
  facet_grid(vars(drv), vars(cyl))
```

## 17.3 Controlling scales

```{r}
p <- mpg2 %>% 
  ggplot(aes(cty, hwy)) +
  geom_abline() +
  geom_jitter(width = 0.1, height = 0.1) 

p + 
  facet_wrap(vars(cyl))

p +
  facet_wrap(vars(cyl), scales = "free")
```

```{r}
economics_long

economics_long %>%
  ggplot(aes(date, value)) + 
  geom_line() + 
  facet_wrap(
    vars(variable),
    scales = "free_y",
    ncol   = 1
  )
```

```{r}
mpg3 <- mpg2 %>%
  mutate(
    model        = as_factor(model),
    manufacturer = as_factor(manufacturer)
  )

mpg3 %>%
  ggplot(aes(cty, fct_reorder(model, cty))) + 
  geom_point() +
  facet_grid(
    rows = vars(
      fct_reorder(
        manufacturer,
        cty,
        .desc = TRUE
      )
    ),
    scales = "free",
    space  = "free"
  ) +
  theme(strip.text.y = element_text(angle = 0)) +
  labs(y = "model")
```

## 17.4 Missing faceting variables

```{r}
tbl1 <- tibble(
  x      = 1:3,
  y      = 1:3,
  gender = c("f", "f", "m")
)

tbl2 <- tibble(x = 2, y = 2)

tbl1 %>%
  ggplot(aes(x, y)) + 
  geom_point(
    data  = tbl2,
    color = "red",
    size  = 2
  ) + 
  geom_point() + 
  facet_wrap(vars(gender))
```

## 17.5 Grouping vs. faceting

```{r}
tbl <- data.frame(
  x = rnorm(120, c(0, 2, 4)),
  y = rnorm(120, c(1, 2, 1)),
  z = letters[1:3]
) %>% as_tibble()

# Grouping
p <- tbl %>%
  ggplot(aes(x, y))

p +
  geom_point(aes(color = z)) +
  labs(title = "Grouping")

# Faceting
p +
  geom_point() + 
  facet_wrap(vars(z)) +
  labs(title = "Faceting")

# Faceting with means
tbl_sum <- tbl %>%
  summarize(
    x   = mean(x),
    y   = mean(y),
    .by = z
  ) %>%
  rename(z2 = z)

p + 
  geom_point() + 
  geom_point(
    data       = tbl_sum,
    aes(color  = z2),
    size       = 4
  ) + 
  facet_wrap(vars(z)) +
  labs(title = "Faceting with Means")

# Grouping + faceting
tbl3 <- tbl %>% 
  select(-z)

p +
  geom_point(data = tbl3, color = "grey70") +
  geom_point(aes(color = z)) + 
  facet_wrap(vars(z)) +
  labs(title = "Grouping + Faceting")
```

## 17.6 Continuous variables

```{r}
mpg4 <- mpg2 %>% 
  mutate(
    # Bins of width 1
    disp_w = displ %>% cut_width(1),
    # Six bins of equal length
    disp_i = displ %>% cut_interval(6),
    # Six bins containing equal numbers of points
    disp_n = displ %>% cut_number(6)
  )

plot <- mpg4 %>% 
  ggplot(aes(cty, hwy)) +
  geom_point() +
  labs(
    x = NULL,
    y = NULL
  )

plot +
  facet_wrap(vars(disp_w), nrow = 1)

plot +
  facet_wrap(vars(disp_i), nrow = 1)

plot +
  facet_wrap(vars(disp_n), nrow = 1)
```

## 17.7 Exercises

1.
```{r}
carats <- diamonds %>%
  mutate(carat = carat %>% as.integer())

carats %>% 
  ggplot(
    aes(
      price,
      color = as.factor(carat)
    )
  ) +
  geom_freqpoly() +
  facet_wrap(vars(cut), scales = "free_y") +
  labs(color = "carat")

carats %>%
  ggplot(aes(price, color = cut)) +
  geom_freqpoly() +
  facet_wrap(vars(carat), scales = "free_y")
```

2.
```{r}
p <- diamonds %>%
  ggplot(aes(carat, price, color = color)) +
  geom_point()

p

p +
  facet_wrap(vars(color))

diamonds2 <- diamonds %>% 
  select(-color)

diamonds %>%
  ggplot(aes(carat, price)) +
  geom_point(data = diamonds2, color = "grey70") +
  geom_point(aes(color = color)) + 
  facet_wrap(vars(color))
```

4.
```{r}
mpg2 %>% 
  ggplot(aes(displ, hwy)) +
  geom_point() +
  geom_smooth(
    data = mpg2 %>% select(-class),
    se = FALSE
  ) +
  facet_wrap(vars(class))
```
