---
title: "Wickham, Hadley - ggplot2: Elegant Graphics for Data Analysis (3rd ed.), Chapter 21 - Extending ggplot2"
author: "Antti Rask"
date: "2023-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 21 Extending ggplot2

```{r}
library(tidyverse)
```

## 21.1 New themes

### 21.1.1 Modifying themes

```{r}
theme_minimal <- function(
    base_size      = 11, 
    base_family    = "", 
    base_line_size = base_size/22, 
    base_rect_size = base_size/22
) {
    theme_bw(
        base_size      = base_size, 
        base_family    = base_family, 
        base_line_size = base_line_size, 
        base_rect_size = base_rect_size
    ) %+replace%
        theme(
            axis.ticks        = element_blank(), 
            legend.background = element_blank(), 
            legend.key        = element_blank(), 
            panel.background  = element_blank(), 
            panel.border      = element_blank(), 
            strip.background  = element_blank(), 
            plot.background   = element_blank(), 
            complete          = TRUE
        )
}
```

```{r}
theme_background <- function(background = "white", ...) {
    theme_minimal(...) %+replace%
        theme(
            plot.background = element_rect(
                fill   = background,
                colour = background
            ),
            complete = TRUE
        )
}

base <- mpg %>% 
    ggplot(aes(displ, hwy)) +
    geom_point()

base +
    theme_minimal(base_size = 14)

base +
    theme_background(base_size = 14)

base +
    theme_background(
        base_size = 14,
        background = "grey70"
    )
```

### 21.1.2 Complete themes

```{r}
# good 
theme_predictable <- function(...) {
    theme_classic(...) %+replace% 
        theme(
            axis.line.x = element_line(color = "blue"),
            axis.line.y = element_line(color = "orange"),
            complete    = TRUE
        )
}

# bad
theme_surprising <- function(...) {
    theme_classic(...) %+replace% 
        theme(
            axis.line.x = element_line(color = "blue"),
            axis.line.y = element_line(color = "orange")
        )
}

base +
    theme_classic()

base +
    theme_predictable()

base +
    theme_surprising()

base +
    theme_classic() +
    theme(axis.line = element_blank())

base +
    theme_predictable() +
    theme(axis.line = element_blank())

base +
    theme_surprising() +
    theme(axis.line = element_blank())

base + 
    theme_classic() +
    theme(
        axis.line.x = element_line(color = "blue"),
        axis.line.y = element_line(color = "orange"),
        axis.line   = element_blank()
    )
```

### 21.1.3 Defining theme elements

```{r}
register_theme_elements(
    ggxyz.panel.annotation = element_text(
        color = "blue", 
        hjust = 0.95, 
        vjust = 0.05
    ),
    element_tree = list(
        ggxyz.panel.annotation = el_def(
            class   = "element_text", 
            inherit = "text"
        )
    )
)

coord_annotate <- function(label = "panel annotation") {
    ggproto(NULL, CoordCartesian,
            limits    = list(x = NULL, y = NULL),
            expand    = TRUE,
            default   = FALSE,
            clip      = "on",
            render_fg = function(panel_params, theme) {
                element_render(
                    theme   = theme, 
                    element = "ggxyz.panel.annotation", 
                    label   = label
                )
            }
    )
}

p <- base +
    coord_annotate("annotation in blue")

p

p +
    theme_dark()
```

## 21.2 New stats

### 21.2.1 Creating stats

```{r}
StatChull <- ggproto(
    "StatChull",
    Stat,
    compute_group = function(data, scales) {
        data[chull(data$x, data$y), , drop = FALSE]
    },
    required_aes = c("x", "y")
)

stat_chull <- function(
    mapping     = NULL,
    data        = NULL,
    geom        = "polygon",
    position    = "identity",
    na.rm       = FALSE,
    show.legend = NA, 
    inherit.aes = TRUE,
    ...
) {
    layer(
        stat        = StatChull, 
        data        = data, 
        mapping     = mapping, 
        geom        = geom, 
        position    = position, 
        show.legend = show.legend, 
        inherit.aes = inherit.aes, 
        params      = list(na.rm = na.rm, ...)
    )
}

mpg %>%
    ggplot(aes(displ, hwy)) +
    geom_point() +
    stat_chull(fill = NA, colour = "black")

ggplot(mpg, aes(displ, hwy, colour = drv)) + 
    geom_point() + 
    stat_chull(fill = NA)
```

### 21.2.2 Modifying parameters and data

```{r}
common_bandwidth <- function(data) {
    split_data <- split(data$x, data$group)
    bandwidth  <- mean(vapply(split_data, bw.nrd0, numeric(1)))
    return(bandwidth)
}

StatDensityCommon <- ggproto(
    "StatDensityCommon",
    Stat,
    required_aes = "x",
    setup_params = function(data, params) {
        if(is.null(params$bandwith)) {
            params$bandwidth <- common_bandwidth(data)
            message("Picking bandwidth of ", signif(params$bandwidth, 3))
        }
        return(params)
    },
    compute_group = function(data, scales, bandwidth = 1) {
        d <- density(data$x, bw = bandwidth)
        return(data.frame(x = d$x, y = d$y))
    }  
)

stat_density_common <- function(
    mapping     = NULL,
    data        = NULL,
    geom        = "line",
    position    = "identity",
    na.rm       = FALSE,
    show.legend = NA,
    inherit.aes = TRUE,
    bandwidth   = NULL,
    ...
) {
    layer(
        stat        = StatDensityCommon, 
        data        = data, 
        mapping     = mapping, 
        geom        = geom, 
        position    = position, 
        show.legend = show.legend, 
        inherit.aes = inherit.aes, 
        params      = list(
            bandwidth = bandwidth, 
            na.rm     = na.rm,
            ...
        )
    )
}

mpg %>%
    ggplot(aes(displ, colour = drv)) +
    stat_density_common()
```

## 21.3 New geoms

### 21.3.1 Modifying geom defaults

```{r}
GeomPolygonHollow <- ggproto(
    "GeomPolygonHollow",
    GeomPolygon,
    default_aes = aes(
        colour    = "black", 
        fill      = NA, 
        linewidth = 0.5,
        linetype  = 1,
        alpha     = NA
    )
)

geom_chull <- function(
    mapping     = NULL,
    data        = NULL,
    stat        = "chull",
    position    = "identity",
    na.rm       = FALSE,
    show.legend = NA,
    inherit.aes = TRUE,
    ...
) {
    layer(
        geom        = GeomPolygonHollow, 
        data        = data, 
        mapping     = mapping, 
        stat        = stat, 
        position    = position, 
        show.legend = show.legend, 
        inherit.aes = inherit.aes,
        params      = list(na.rm = na.rm, ...)
    )
}

mpg %>%
    ggplot(aes(displ, hwy)) +
    geom_chull() +
    geom_point()
```

### 21.3.2 Modifying geom data

```{r}
GeomSpike <- ggproto(
    "GeomSpike",
    GeomSegment,
    
    # Specify the required aesthetics                   
    required_aes = c("x", "y", "angle", "radius"),
    
    # Transform the data before any drawing takes place
    setup_data = function(data, params) {
        transform(
            data,
            xend = x + cos(angle) * radius,
            yend = y + sin(angle) * radius
        )
    }
)

geom_spike <- function(
    mapping     = NULL,
    data        = NULL,
    stat        = "identity",
    position    = "identity",
    ...,
    na.rm       = FALSE,
    show.legend = NA,
    inherit.aes = TRUE
) {
  layer(
    data        = data, 
    mapping     = mapping, 
    geom        = GeomSpike, 
    stat        = stat, 
    position    = position, 
    show.legend = show.legend, 
    inherit.aes = inherit.aes, 
    params      = list(na.rm = na.rm, ...)
  )
}

tbl <- tibble(
  x      = 1:10,
  y      = 0,
  angle  = seq(from = 0, to = 2 * pi, length.out = 10),
  radius = seq(from = 0, to = 2, length.out = 10)
)

tbl %>%
ggplot(aes(x, y)) +
  geom_spike(aes(angle = angle, radius = radius)) + 
  coord_equal()
```

### 21.3.3 Combining multiple geoms

```{r}
library(grid)

GeomBarbell <- ggproto(
    "GeomBarbell",
    Geom,
    required_aes = c("x", "y", "xend", "yend"),
    default_aes  = aes(
        colour    = "black",
        linewidth = .5,
        size      = 2,
        linetype  = 1,
        shape     = 19,
        fill      = NA,
        alpha     = NA,
        stroke    = 1
    ),
    
    draw_panel = function(data, panel_params, coord, ...) {
                           
        # Transformed data for the points
        point1 <- transform(data) 
        point2 <- transform(data, x = xend, y = yend)    
        
        # Return all three components
        gList(
            GeomSegment$draw_panel(data, panel_params, coord, ...),
            GeomPoint$draw_panel(point1, panel_params, coord, ...),
            GeomPoint$draw_panel(point2, panel_params, coord, ...)
        )
    }
)

geom_barbell <- function(
    mapping     = NULL,
    data        = NULL,
    stat        = "identity",
    position    = "identity", 
    ...,
    na.rm       = FALSE,
    show.legend = NA,
    inherit.aes = TRUE
) {
    layer(
        data        = data, 
        mapping     = mapping, 
        stat        = stat, 
        geom        = GeomBarbell, 
        position    = position, 
        show.legend = show.legend, 
        inherit.aes = inherit.aes, 
        params      = list(na.rm = na.rm, ...)
    )
}

tbl  <- tibble(x = 1:10, xend = 0:9, y = 0, yend = 1:10)

base <- tbl %>% 
    ggplot(aes(x, y, xend = xend, yend = yend))

base +
    geom_barbell()

base +
    geom_barbell(shape = 4, linetype = "dashed")
```

## 21.5 New scales

```{r}
random_colours <- function(n) {
    sample(colours(distinct = TRUE), n, replace = TRUE)
}

scale_fill_random <- function(..., aesthetics = "fill") {
    discrete_scale(
        aesthetics = aesthetics,
        scale_name = "random", 
        palette    = random_colours
    )
}

mpg %>%
    ggplot(aes(hwy, class, fill = class)) + 
    geom_violin(show.legend = FALSE) +
    scale_fill_random()
```

## 21.6 New positions

```{r}
normal_transformer <- function(x, sd) {
    function(x) {x + rnorm(length(x), sd = sd)}
}

PositionJitterNormal <- ggproto(
    'PositionJitterNormal',
    Position,
    
    # We need an x and y position aesthetic                              
    required_aes = c('x', 'y'),
    
    # By using the "self" argument we can access parameters that the 
    # user has passed to the position, and add them as layer parameters
    setup_params = function(self, data) {
        list(
            sd_x = self$sd_x, 
            sd_y = self$sd_y
        )
    },
    
    # When computing the layer, we can read the standard deviation 
    # parameters off the param list, and use them to transform the
    # position aesthetics
    compute_layer = function(data, params, panel) {
        
        # construct transformers for the x and y position scales 
        x_transformer <- normal_transformer(x, params$sd_x)
        y_transformer <- normal_transformer(y, params$sd_y)
        
        # return the transformed data
        transform_position(
            df      = data,
            trans_x = x_transformer,  
            trans_y = y_transformer
        )
    }
)

position_jitternormal <- function(sd_x = .15, sd_y = .15) {
    ggproto(NULL, PositionJitterNormal, sd_x = sd_x, sd_y = sd_y)
}

tbl <- data.frame(
    x = sample(1:3, 1500, TRUE),
    y = sample(1:3, 1500, TRUE)
)

tbl %>%
    ggplot(aes(x, y)) + geom_point(position = position_jitter())

tbl %>%
    ggplot(aes(x, y)) + geom_point(position = position_jitternormal())

```

## 21.7 New facets

```{r}
library(rlang)

FacetScatter <- ggproto(
    "FacetScatter",
    FacetWrap,
    
    # This isn't important to the example: all we're doing is
    # forcing all panels to use fixed scale so that the rest
    # of the example can be kept simple
    setup_params = function(data, params) {
        params      <- FacetWrap$setup_params(data, params)
        params$free <- list(x = FALSE, y = FALSE)
        return(params)
    },                      
    
    # The compute_layout() method does the work
    compute_layout = function(data, params) {
        
        # create a data frame with one column per facetting 
        # variable, and one row for each possible combination
        # of values (i.e., one row per panel)
        panels <- combine_vars(
            data = data,
            env  = params$plot_env, 
            vars = params$facets, 
            drop = FALSE
        )
        
        # Create a data frame with columns for ROW and COL, 
        # with one row for each possible cell in the panel grid
        locations <- expand.grid(ROW = 1:params$nrow, COL = 1:params$ncol)
        
        # Randomly sample a subset of the locations
        shuffle <- sample(nrow(locations), nrow(panels))
        
        # Assign each panel a location                      
        layout <- data.frame(
            # panel identifier
            PANEL   = 1:nrow(panels),
            # row number for the panels
            ROW     = locations$ROW[shuffle],
            # column number for the panels
            COL     = locations$COL[shuffle],
            # all x-axis scales are fixed
            SCALE_X = 1L,
            # all y-axis scales are fixed
            SCALE_Y = 1L
        )
        
        # Bind the layout information with the panel identification
        # and return the resulting specification
        return(cbind(layout, panels))
    }                      
)

facet_scatter <- function(
    facets,
    nrow,
    ncol,
    strip.position = "top", 
    labeller       = "label_value"
) {
    
    ggproto(
        NULL,
        FacetScatter,
        params = list(
            facets         = quos_auto_name(facets),
            strip.position = strip.position,
            labeller       = labeller, 
            ncol           = ncol, 
            nrow           = nrow
        )
    )
}

mpg %>%
    ggplot(aes(displ, hwy)) + 
    geom_point() + 
    facet_scatter(vars(manufacturer), nrow = 5, ncol = 6)
```
